[build]
  base = "api"
  functions = "netlify/functions"

[dev]
  base = "api"
  functions = "netlify/functions"

[functions]
  node_bundler = "nft"
  included_files = ["json/**"]

[[redirects]]
  from = "/api/graphql"
  to = "/.netlify/functions/graphql"
  status = 200
