[build]
  publish = "."
  functions = "netlify/functions"
  command = "npm install && cp -r ../json netlify/functions/json"

[dev]
  functions = "netlify/functions"

[functions]
  node_bundler = "nft"
  included_files = ["json/**"]

[[redirects]]
  from = "/api/graphql"
  to = "/.netlify/functions/graphql"
  status = 200
